### ISSUE TITLE
Does not work without OPENAPI_KEY in environment

### ISSUE THREAD

**Issue by munish7771** [TextQLLabs/dbt-doc-py#4]
Installation - 

`pip3 install dbt-doc-py`

DBT environment - 

[link to repo](https://github.com/munish7771/magicschool-dbt)

Error log- 

`dbt-doc-py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Running DBT docs generate...
DBT docs successfully generated!
You haven't specified an API Key. No worries, this one's on TextQL!
In return, please type your email address. We don't collect any other data, nor sell your email to third parties.
If you're okay with this, press enter. Otherwise, type 'no' and set the OPENAI_API_KEY environment variable.
Email (type no to abort): munish7771@gmail.com
[?] Select the models you want to document: (Press Spacebar to select, Enter to confirm) : 
 > [X] model.magicschool.my_third_dbt_model
   [ ] model.magicschool.my_second_dbt_model
   [ ] seed.magicschool.customers
   [ ] model.magicschool.my_first_dbt_model

Generating docs for: my_third_dbt_model
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
'UserInfo' object has no attribute 'key'
OAI request to my_third_dbt_model failed: 'UserInfo' object has no attribute 'key'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/dbt-doc-py", line 33, in <module>
    sys.exit(load_entry_point('dbt-doc-py==0.1.19', 'console_scripts', 'dbt-doc-py')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 864, in run_async_main
    asyncio.run(async_main(sys.argv[1:]))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 858, in async_main
    await main(argv)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 841, in main
    summarized_nodes = await asyncio.gather(*[open_ai_summarize(env, r_deps, pair[1]) for pair in nodes_to_process])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 322, in open_ai_summarize
    raise e  # Reraise the exception to trigger a retry
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 304, in open_ai_summarize
    tbl_result, col_result = await asyncio.gather(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 279, in run_openai_request
    raise e    
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dbt_doc_py/dbt_doc_py.py", line 257, in run_openai_request
    if env.api_key.key:
AttributeError: 'UserInfo' object has no attribute 'key'`

Troubleshooting -

- [x] Runs successfully if you add your own OPENAI_API_KEY in environment.
- [x] Tried running with local installation of dbt, rather than docker. Same issue persists.

**Comment by TenKenZero** [comment]
A new version was released, fixing this error.

https://pypi.org/project/dbt-doc-py/0.1.25/
